Update activity.md
elsa-workflows/elsa-documentation pull request #17
Opened 2023-07-09 07:40 UTC by adolfie450

Added code Outcomes Example

2023-07-09 07:41 UTC, adolfie450 commented
@dotnet-policy-service agree

2023-07-09 09:41 UTC, sfmskywalker requested changes
Thank you for taking the time to enrich the documentation!
I had a few small requests for your consideration.

2023-07-09 09:41 UTC, sfmskywalker commented on v3/src/pages/docs/core-concepts/activity.md
> +Custom Activity outcome Nodes can be defined as follows by Annotatting the the Metadata with the "FlowNode" attribute as follows:
Small typo in "Annotatting" and double occurence of "the" ("the the").
Also, perhaps the capitalization can be changed like this:

"Custom activity outcomes can be defined by annotating the class with the `FlowNodeAttribute` attribute as follows:"

2023-07-09 09:41 UTC, sfmskywalker commented on v3/src/pages/docs/core-concepts/activity.md
> +This produces 2 outcomes of the Activity a in this case a Pass or Fail, this can be implemented as follows
"This produces two outcomes of the activity. In this case, a "Pass" or "Fail". To produce an outcome, use the `CompleteActivityAsync` method, as follows:"

2023-07-09 09:41 UTC, sfmskywalker commented on v3/src/pages/docs/core-concepts/activity.md
> +       "Demo", "Demo", "Simple activity ")]
Let's put these arguments on the same line as the Activity attribute:

```
[Activity("Demo", "Demo", "Simple activity ")]
```

2023-07-09 09:41 UTC, sfmskywalker commented on v3/src/pages/docs/core-concepts/activity.md
> +       "Demo", "Demo", "Simple activity ")]
Let's put these arguments on the same line as the Activity attribute:

```
[Activity("Demo", "Demo", "Simple activity ")]
```

2023-10-17 20:15 UTC, sfmskywalker approved these changes

2023-10-17 20:25 UTC, merged